version: "3.8"
services:
  frontend:
    container_name: portafolio-app
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - frontend-network
    volumes: # comentar en produccion
      - ./:/usr/src/app/ # comentar en produccion
    ports:
      - "80:3000"
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      # - "80:80" # descomentar en produccion
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - proxy

volumes:
  certs:
  vhostd:
  html:
  acme:

networks:
  frontend-network:
    external: false
    name: frontend-network
  proxy:
    external: false
    name: proxy
