version: "3.8"
services:
  frontend:
    container_name: portafolio-app
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - frontend-network
      - proxy
    environment:
      - WPN_WAIT_UNTIL=60
      - DEBUG=True
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=ramonb44.dev # descomentar en produccion
      - LETSENCRYPT_HOST=ramonb44.dev
      - VIRTUAL_ROOT=/home/lordhunter/Portafolio

volumes:
  app-root:
    name: nginx_app-root
    external: true

networks:
  proxy:
    name: proxy
    external: true
  frontend-network:
    name: frontend-network
    external: false
